### ISSUE TITLE
dont persist data

### ISSUE THREAD

**Issue by brunokunace** [magently/docker#1]
Hi, i try to use this image, but all time when i restart a docker-compose, all instalation procede again.

PS.: I need to change admin password everytime too, have way to set this on enviroment?

my docker-compose

```
version: '2'

services:
  # MySQL container
  magento-db:
    container_name: magento-db
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento

  # App container
  magento-app:
    container_name: magento-app
    image: magently/magento2
    links:
      - magento-db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./packages/:/app/packages/
    environment:
      - MYSQL_HOST=magento-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento

```

Thanks!
